spring.application.name=Url-Shortener

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=true

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
