ALTER TABLE click_log
    ALTER COLUMN ip_address TYPE VARCHAR(255),
    ALTER COLUMN user_agent TYPE VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN first_name TYPE VARCHAR(255),
    ALTER COLUMN last_name TYPE VARCHAR(255),
    ALTER COLUMN email TYPE VARCHAR(500),
    ALTER COLUMN status TYPE VARCHAR(255),
    ALTER COLUMN role TYPE VARCHAR(255);
